import mongoose from 'mongoose';

const routePlanSchema = new mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  date: Date,
  stops: [{
    name: String,
    type: { type: String, enum: ['breakfast', 'visit', 'lunch', 'dinner', 'event'] },
    place: { type: mongoose.Schema.Types.ObjectId, ref: 'Place' },
    time: String
  }],
  isAutoGenerated: Boolean
}, { timestamps: true });

export default mongoose.model('RoutePlan', routePlanSchema);
