// src/controllers/routeController.js
import asyncHandler from 'express-async-handler';
import Place from '../models/Place.js';
import RoutePlan from '../models/RoutePlan.js';
import upload from '../config/multer.js';
/**
 * Generador simple:
 * - recibe una ubicación (lng, lat) y un tipo de plan (full-day)
 * - busca lugares por categorías típicas (breakfast, visit, lunch, visit, dinner)
 * - ordena por distancia y arma stops
 * - si isAutoGenerated==false, permite crear manualmente
 */

export const autoGenerateRoute = asyncHandler(async (req, res) => {
  const { lng, lat, date = new Date(), radius = 20000 } = req.body;
  if (!lng || !lat) {
    res.status(400);
    throw new Error('lng y lat requeridos');
  }

  const categoriesForDay = [
    { type: 'breakfast', category: 'breakfast' },
    { type: 'visit', category: 'sightseeing' },
    { type: 'lunch', category: 'restaurant' },
    { type: 'visit', category: 'museum' },
    { type: 'dinner', category: 'restaurant' }
  ];

  // For each category, find nearest
  const stops = [];
  for (const cat of categoriesForDay) {
    const found = await Place.findOne({
      category: cat.category,
      coordinates: {
        $nearSphere: {
          $geometry: { type: 'Point', coordinates: [parseFloat(lng), parseFloat(lat)] },
          $maxDistance: parseInt(radius, 10)
        }
      }
    });
    if (found) {
      stops.push({
        name: found.name,
        type: cat.type,
        place: found._id,
        time: null
      });
    }
  }

  const route = new RoutePlan({
    user: req.user._id,
    date,
    stops,
    isAutoGenerated: true
  });
  await route.save();
  res.status(201).json(route);
});

// Save manual route
export const saveManualRoute = asyncHandler(async (req, res) => {
  const { stops, date } = req.body;
  const route = new RoutePlan({
    user: req.user._id,
    date: date || new Date(),
    stops,
    isAutoGenerated: false
  });
  await route.save();
  res.status(201).json(route);
});

// Get user routes
export const getUserRoutes = asyncHandler(async (req, res) => {
  const routes = await RoutePlan.find({ user: req.user._id }).populate('stops.place');
  res.json(routes);
});
